# -*- coding: utf-8 -*-
"""Feature guide: Debts, Splits & Shared Subscriptions. Run: python gen_debt.py"""
import os, _docgen as dg

d = dg.FeatureDoc(
    kicker="POTRACES · FEATURE GUIDE",
    title="Debts, Splits & Shared Subscriptions",
    subtitle="Who owes whom, splitting bills, and cost-sharing — and how it all stays in sync",
    meta="Updated June 2026 · code-accurate reference",
)

d.h("Overview")
d.p("The debt system tracks money between you and other people in two directions, with an "
    "append-only audit trail, optional wallet movement, and a linked transaction for every "
    "payment. It also powers **splitting a bill** and **shared subscriptions** (Netflix/Spotify "
    "cost-sharing). The 'other person' is just a saved contact — there is **no two-user "
    "shared-debt sync**; everything lives on your device(s).")

# 1. CONCEPT
d.h("1.  The concept — directions, statuses, colours")
d.h2("Two directions")
d.table(
    ["Direction", "Meaning", "Colour"],
    [
        [("I Owe", dg.TERRA_TINT, dg.TERRA), "Money I owe someone (my liability)", "Terracotta #C1694F"],
        [("They Owe Me", dg.OLIVE_TINT, dg.OLIVE), "Money someone owes me (my asset)", "Olive #4F5104"],
    ],
    widths=[1.6, 4.0, 2.0],
)
d.h2("Three statuses (derived, never set by hand)")
d.table(
    ["Status", "When", "Colour"],
    [
        [("Pending", dg.GOLD_TINT, dg.GOLD), "Created, nothing paid yet", "Bright gold #DEAB22"],
        [("Partial", dg.GOLD_TINT, dg.GOLD), "Some paid, not all", "Bronze #B2780A"],
        [("Settled", dg.SKY_TINT, dg.SKY), "Fully paid (or netted to zero)", "Sky blue #6BA3BE"],
    ],
    widths=[1.6, 4.0, 2.0],
)
d.callout("The status literal is `pending` (shown 'Pending') — there is no 'unpaid'. Status is "
          "always recomputed from paid vs total, so you settle a debt by recording payment that "
          "covers the rest, not by flipping a switch.", kind="note")

# 2. DATA MODEL
d.h("2.  The Debt data model")
d.table(
    ["Field", "Type", "Meaning"],
    [
        ["id", "string", "Unique id"],
        ["groupId ◦", "string", "Groups all debts with one contact so they net/consolidate"],
        ["contact", "Contact", "The other party { name, phone?, email?, isFromPhone }"],
        ["type", "i_owe | they_owe", "Direction"],
        ["totalAmount", "number", "Full amount of the debt"],
        ["paidAmount", "number", "Sum of payments, capped at total (derived)"],
        ["status", "pending|partial|settled", "Derived from paid vs total"],
        ["description", "string", "Free text ('lunch', 'loan'…)"],
        ["payments", "Payment[]", "Append-only list of payments"],
        ["mode", "personal | business", "Which money flow is used"],
        ["dueDate ◦", "Date", "Optional due date"],
        ["splitId ◦", "string", "Set if generated by a split expense"],
        ["sharedSubId / sharedSubMonth ◦", "string", "Set if generated by a shared subscription"],
        ["editLog ◦", "DebtEdit[]", "Append-only audit of total/description/contact edits"],
        ["isArchived / archivedAt ◦", "—", "Soft-hide without deleting"],
        ["createdAt / updatedAt", "Date", "Timestamps"],
    ],
    widths=[2.3, 1.9, 3.4],
)
d.p("**Payment** = `{ id, amount, date, note?, tipAmount?, linkedTransactionId?, walletId?, "
    "editLog? }`. A self pseudo-contact id `__self__` represents 'me' inside splits and shared "
    "subscriptions.")

# 3. CREATING
d.h("3.  Creating a debt")
d.p("**Where:** the FAB choice sheet → 'add debt'. **Fields:** contact, amount, direction "
    "(I owe / they owe), description, optional category, optional due date.")
d.bullet("**Contact** comes from your **phone contacts** (with permission) or **manual** entry "
         "(name required) via the shared ContactPicker.")
d.bullet("**Auto-grouping:** a new debt to a person who already has an open debt joins that "
         "person's group automatically, so their debts can be paid/netted together.")
d.bullet("Rejects amounts ≤ 0; starts at `paidAmount 0`, status `pending`.")

# 4. PAYMENTS
d.h("4.  Payments — the core flow")
d.p("Recording a payment does up to three things at once:")
d.num("**Records the payment** on the debt (`addPayment`), capping it at the remaining amount — a "
      "debt can never be overpaid in the data; any excess becomes a **tip**.")
d.num("**Moves a wallet** (only if you pick one): **they owe → income → add to wallet**; "
      "**I owe → expense → deduct from wallet**.")
d.num("**Creates a linked transaction** carrying `linkedDebtId` + `linkedPaymentId`, so the "
      "payment shows up in your normal transaction list. The payment points back via "
      "`linkedTransactionId`.")
d.p("Reaching the total flips the debt to **settled** (and marks any linked split participant / "
    "shared-sub member paid).")
d.h2("Tips (overpayment)")
d.p("If you pay more than what's left, the app asks to confirm a **tip**: the debt counts only the "
    "remaining amount; the excess is recorded as `tipAmount` and noted on the transaction "
    "('incl. tip RM x').")
d.h2("Consolidated / group payment (pay everything at once)")
d.bullet("Pays all of a person's open debts in one cash event.")
d.bullet("**Netting:** if the person has both directions and you pay the full net, the smaller "
         "side offsets the larger (settling the overlap); equal amounts net to **zero with no "
         "cash**.")
d.bullet("One transaction is created for the cash leg; the money is **distributed proportionally** "
         "across the net-direction debts so each shows progress. All those payments share one "
         "`linkedTransactionId` (marking them a batch).")

# 5. EDIT AUDIT TRAIL
d.h("5.  Edit audit trail (append-only)")
d.p("Matches the app-wide audit pattern — financial edits are logged, never silently overwritten.")
d.bullet("**Debt-level (`DebtEdit`)** logs changes to **total amount, description, or contact**, "
         "each as `{ editedAt, field, previousValue, newValue }`, only when the value actually "
         "changed.")
d.bullet("**Payment-level (`PaymentEdit`)** snapshots `{ editedAt, previousAmount, previousNote }` "
         "before an amount/note change.")
d.bullet("**UI:** a bronze **'edited'** badge on changed payment rows, and an **Edit History** "
         "section in the payment detail (newest first, 'was RM …').")
d.callout("Sync rule: the side that **initiates** a payment/edit performs the wallet movement; the "
          "linked transaction just mirrors the amount. (There's no second human to reconcile — see "
          "§9.)", kind="note")

# 6. LIFECYCLE
d.h("6.  Status lifecycle, archive & delete")
d.p("**Lifecycle:** pending → partial → settled, always derived from paid vs total. **Archive** "
    "soft-hides a debt (excluded from group ops, rejects new payments) without deleting it.")
d.h2("Deleting a debt — what reverses")
d.bullet("**Blocked** if it has consolidated-batch payments shared with siblings ('remove the "
         "group payment first'), or if it came from a split ('edit/delete the split instead').")
d.bullet("Otherwise it reverses every payment (deletes the linked transactions, reverses the "
         "wallets) and tombstones the debt so it won't resync.")
d.bullet("**Deleting a contact** does NOT delete their debts — it renames them to '(deleted)' "
         "inside the history, preserving the record.")

# 7. SPLITS
d.h("7.  Splits — dividing a bill among people")
d.p("A **SplitExpense** divides a bill equally, by custom amounts, or **item-by-item** (with "
    "optional tax handling). It turns into real debts based on who paid:")
d.table(
    ["Who paid", "What happens"],
    [
        [("I paid", dg.OLIVE_TINT, dg.OLIVE),
         "One expense transaction for the full amount (wallet deducted / credit used), then a "
         "'they owe me' debt for each other person's share — each linked back via splitId."],
        [("Someone else paid", dg.TERRA_TINT, dg.TERRA),
         "One 'I owe' debt for my share to that person — no expense or wallet change for me."],
    ],
    widths=[1.7, 5.9],
)
d.bullet("**Marking a participant paid** routes through the **real payment flow** (opening the "
         "payment modal pre-filled) when a linked debt exists — so it creates a true transaction "
         "and wallet movement, not just a checkbox.")
d.bullet("**Editing a split** cascades correctly: removing a participant deletes their debt; "
         "changing who paid flips direction (tears down & recreates); changing the total updates "
         "the transaction + each debt — but it won't shrink a debt below what's already paid.")
d.bullet("**Receipt-scan wizard** builds an item-based split (saveable as a draft); a WhatsApp "
         "message with a per-item breakdown + optional payment QR can be generated to chase people.")

# 8. SHARED SUBSCRIPTIONS
d.h("8.  Shared subscriptions (Netflix / Spotify cost-sharing)")
d.callout("This feature is fully BUILT — it's the third tab in the debt area with a form, detail, "
          "and price-change sheets. (An old memory note calling it a 'blueprint, build later' is "
          "stale.)", kind="note")
d.bullet("A shared subscription has a name, total, billing cycle/day, and **members** each with a "
         "tag ('owner', 'profile 2') and a share amount; a 'split even' helper keeps shares summing "
         "to the total.")
d.bullet("Each month lazily gets a **month record** using the **effective price** (price changes "
         "are forward-dated and kept in a price history).")
d.bullet("**Generating debts for a month** creates a 'they owe me' debt per member (skipping "
         "yourself). Settling one marks that member paid; deleting the settling payment unmarks them.")
d.bullet("**Price changes** are recorded forward-effective; a specific month's amounts can be "
         "edited retroactively and will cascade to that month's already-generated debts.")
d.callout("Shared subscriptions are **local-only** — they are not in the cloud sync, so losing the "
          "device loses them.", kind="manual")

# 9. LINKED TRANSACTIONS
d.h("9.  Linked transactions & protection")
d.p("Every debt payment shows up in the normal transaction list (income for 'they owe', expense "
    "for 'I owe') via `linkedDebtId` + `linkedPaymentId`. To keep the two sides from drifting:")
d.bullet("The **amount is locked** in the transaction edit sheet — only description + tags are "
         "editable. If an amount edit is somehow forced, it's pushed back into the **debt payment**, "
         "not the wallet.")
d.bullet("**Deletion is blocked** from the Transactions list (swipe, bulk, and single) — you remove "
         "the money by deleting the **payment** on the debt screen, which cascades to the transaction.")

# 10. SYNC + GOTCHAS
d.h("10.  Sync, edge cases & what's manual")
d.h2("Cross-person / cross-device")
d.bullet("**No two-user sharing.** The other party is just a contact; nothing is sent to them.")
d.bullet("**Multi-device backup** (your own account) syncs debts, splits, and contacts to Supabase "
         "(last-write-wins, tombstoned). **Shared subscriptions are not synced.**")
d.h2("Gotchas")
d.bullet("Overpayment is capped in the data; the excess is only a UI tip.")
d.bullet("Consolidated payments are semi-immutable — edit is blocked; remove & re-record instead.")
d.bullet("Split-linked debts can't be deleted individually — edit/delete the split.")
d.bullet("Settled-debt amount edits are blocked to avoid silent un-settling.")
d.bullet("Paying a split from a **credit** wallet uses credit (not a cash deduction).")
d.bullet("**Everything is manual** — recording payments, choosing wallets, generating monthly "
         "shared-sub debts, marking participants, sending reminders, recording price changes. "
         "There is no auto-detection of repayments from bank data.")

# ACTION MAP
d.h("11.  Quick action → effect map")
d.table(
    ["Action", "Wallet / transaction effect"],
    [
        ["Create debt", "None"],
        ["Edit debt", "Re-derives status; logs a DebtEdit"],
        ["Record payment", "Creates a linked transaction, moves the wallet"],
        ["Group/consolidated payment", "One transaction, proportional split, optional netting"],
        ["Edit payment", "Syncs the transaction amount (wallet only in business mode)"],
        ["Delete payment", "Deletes the transaction, reverses the wallet"],
        ["Delete debt", "Reverses all payments, tombstones"],
        ["Create split (I paid)", "Expense transaction + wallet + one debt per person"],
        ["Generate shared-sub debts", "Creates debts; no money until paid"],
    ],
    widths=[2.6, 5.0],
)

d.rule()
d.p("Source: src/store/debtStore.ts, src/screens/shared/DebtTracking.tsx, src/types/index.ts, "
    "src/constants/index.ts, src/components/common/ContactPicker.tsx, src/components/debt/*, "
    "src/services/personalSync.ts. Full notes: docs/research/debt-split-feature-reference.md.",
    size=8.5, color=dg.MUTED, italic=True)

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "03-Debts-Splits-Shared-Subscriptions.docx")
d.save(out)
print("WROTE:", out)
